package kotlinx.schema.generator.reflect

import kotlinx.schema.generator.core.ir.Introspections
import kotlinx.schema.generator.core.ir.TypeRef
import kotlin.reflect.KClass
import kotlin.reflect.KFunction
import kotlin.reflect.KProperty
import kotlin.reflect.KProperty1
import kotlin.reflect.KType
import kotlin.reflect.KVisibility
import kotlin.reflect.full.IllegalCallableAccessException
import kotlin.reflect.full.allSuperclasses
import kotlin.reflect.full.primaryConstructor
import kotlin.reflect.jvm.javaMethod
import kotlin.reflect.jvm.kotlinFunction

/**
 * Gets the [KType.classifier], ensuring it is a [KClass].
 */
internal val KType.klass: KClass<*>
    get() {
        return requireNotNull(classifier as? KClass<*>) {
            "Unsupported classifier: $classifier. " +
                "Only KClass classifiers are supported. Type parameters and other classifiers " +
                "cannot be introspected using reflection."
        }
    }

/**
 * Finds a property in a class by name.
 * Used when extracting metadata from constructor parameters to find corresponding property annotations.
 *
 * @param klass The class to search in
 * @param propertyName The name of the property to find
 * @return The property if found, null otherwise
 */
internal fun findPropertyByName(
    klass: KClass<*>,
    propertyName: String,
): KProperty<*>? =
    klass.members
        .filterIsInstance<KProperty<*>>()
        .firstOrNull { it.name == propertyName }

/**
 * Checks whether the given list of annotations contains a recognized ignore marker
 * (e.g., `@SchemaIgnore`, `@SerialSchemaIgnore`, `@JsonIgnoreType`).
 *
 * @see [Introspections.isIgnoreAnnotation]
 */
internal fun isSchemaIgnored(annotations: List<Annotation>): Boolean =
    annotations.any { annotation ->
        val name = annotation.annotationClass.simpleName ?: return@any false
        Introspections.isIgnoreAnnotation(name)
    }

/**
 * Extracts description from annotations.
 *
 * @see [Introspections.getDescriptionFromAnnotation]
 */
internal fun extractDescription(annotations: List<Annotation>): String? =
    annotations.firstNotNullOfOrNull { annotation ->
        val annotationName = annotation.annotationClass.simpleName ?: return@firstNotNullOfOrNull null
        val annotationArguments =
            buildList {
                annotation.annotationClass.members
                    .filterIsInstance<KProperty1<Annotation, *>>()
                    .forEach { property ->
                        val value =
                            try {
                                property.get(annotation)
                            } catch (_: IllegalCallableAccessException) {
                                fallbackViaJavaReflection(annotation, property) ?: return@forEach
                            } catch (_: IllegalAccessException) {
                                fallbackViaJavaReflection(annotation, property) ?: return@forEach
                            }
                        add(property.name to value)
                    }
            }
        Introspections.getDescriptionFromAnnotation(annotationName, annotationArguments)
    }

/**
 * KProperty1.get() wraps java.lang.IllegalAccessException in
 * kotlin.reflect.full.IllegalCallableAccessException when the annotation
 * interface is non-public (e.g. package-private for Kotlin `internal`
 * annotations from external modules). Fall back to Java reflection on
 * the proxy class, which is always accessible.
 * Returns null when the fallback itself fails; null is safe here because
 * Java annotation elements cannot return null values.
 */
private fun fallbackViaJavaReflection(
    annotation: Annotation,
    property: KProperty1<Annotation, *>,
): Any? =
    try {
        val javaMethod = annotation.javaClass.getDeclaredMethod(property.name)
        javaMethod.isAccessible = true
        javaMethod.invoke(annotation)
    } catch (_: ReflectiveOperationException) {
        null
    } catch (_: SecurityException) {
        null
    }

/**
 * Returns a new [TypeRef] with the specified nullable flag.
 */
internal fun TypeRef.withNullable(nullable: Boolean): TypeRef =
    when (this) {
        is TypeRef.Inline -> copy(nullable = nullable)
        is TypeRef.Ref -> copy(nullable = nullable)
    }

/**
 * Finds effective primary constructor of a class, filtering synthetic constructors generated by kotlinx.serialization.
 */
internal fun findPrimaryConstructor(klass: KClass<*>): KFunction<Any>? {
    /**
     * Check if this is a kotlinx.serialization generated synthetic constructor
     * with a SerializationConstructorMarker param.
     */
    fun KFunction<Any>.isSyntheticSerializationConstructor(): Boolean =
        parameters.any { param ->
            (param.type.classifier as? KClass<*>)?.qualifiedName ==
                "kotlinx.serialization.internal.SerializationConstructorMarker"
        }

    val constructor =
        klass.primaryConstructor
            ?: klass.constructors
                .filterNot { it.visibility == KVisibility.PRIVATE }
                .firstOrNull() // If no primary defined, fallback to the first one
            ?: return null

    return if (constructor.isSyntheticSerializationConstructor()) {
        // Find the real constructor without the SerializationConstructorMarker param
        klass.constructors
            .filterNot { it.visibility == KVisibility.PRIVATE }
            .firstOrNull { ctor -> ctor != constructor && !ctor.isSyntheticSerializationConstructor() }
    } else {
        constructor
    }
}

/**
 * Retrieves a list of methods that are implemented by the current function within its class hierarchy.
 */
internal fun KFunction<*>.findImplementedMethods(): List<KFunction<*>> {
    val javaMethod = this.javaMethod ?: return emptyList()
    val methodName = javaMethod.name
    val parameterTypes = javaMethod.parameterTypes

    return javaMethod.declaringClass.kotlin.allSuperclasses
        .toList()
        .mapNotNull { superclass ->
            try {
                @Suppress("SpreadOperator")
                superclass.java
                    .getDeclaredMethod(methodName, *parameterTypes)
                    .kotlinFunction
                    ?.takeIf { it != this }
            } catch (_: NoSuchMethodException) {
                null
            }
        }
}
